name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
      
      - name: Disable Jekyll
        run: |
          git config user.name NicolasDesnoust
          git config user.email desnoust.nicolas451@gmail.com
          git checkout gh-pages
          touch .nojekyll
          git add .nojekyll
          git commit -m "CI: désactivation automatique de Jekyll"
          git push