name: Scully Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Disable Jekyll
        run: mkdir -p ./dist/static/ && touch ./dist/static/.nojekyll
      
      - uses: cmgriffing/scully-gh-pages-action@v9
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          build-args: --prod